name: Terraform Validate

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4
    
    - name: Terraform Init
      run: |
        if [ -d "my-terraform-project" ]; then
          cd my-terraform-project
          terraform init
        else
          echo "Directory my-terraform-project not found. Skipping Terraform initialization."
        fi

    - name: Validate Terraform
      run: |
        if [ -d "my-terraform-project" ]; then
          cd my-terraform-project
          if ! terraform validate; then
            echo "Terraform validation failed."
            exit 1
          fi
          echo "Terraform validation succeeded."
        else
          echo "Directory my-terraform-project not found, attempting to validate .terraform.lock.hcl instead."
          if [ ! -f "my-terraform-project/.terraform.lock.hcl" ]; then
            echo "Lock file not found!"
            exit 1
          fi
          echo "Lock file found and verified."
        fi

    - name: Check Lock File
      run: |
        if [ -d "my-terraform-project" ]; then
          cd my-terraform-project
        fi
        if [ ! -f ".terraform.lock.hcl" ]; then
          echo "Lock file not found!"
          exit 1
        fi
        echo "Lock file found and verified."
